### ISSUE TITLE
any() takes 1 positional argument but 2 were given error

### ISSUE THREAD

**Issue by abs-yy** [barricklab/pLannotate#23]
Hi, thanks for the great software. 
I was testing pLannotate on my plasmids when I hit this error. I also get this error using the pUC19 fasta file from the repository, so I am presuming that this is not a problem from my own plasmids. The pLannotate was installed through conda.
```

% plannotate --version
plannotate, version 1.2.0

% plannotate batch -i tmp/pUC19.fa --output tmp -d --file_name tmp_plannotate --html
2023-04-28 09:16:35.350
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /home/abs/anaconda3/envs/bio/bin/plannotate [ARGUMENTS]
Traceback (most recent call last):
  File "/home/abs/anaconda3/envs/bio/bin/plannotate", line 10, in <module>
    sys.exit(main())
  File "/home/abs/anaconda3/envs/bio/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/abs/anaconda3/envs/bio/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/abs/anaconda3/envs/bio/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/abs/anaconda3/envs/bio/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/abs/anaconda3/envs/bio/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/abs/anaconda3/envs/bio/lib/python3.8/site-packages/plannotate/pLannotate.py", line 116, in main_batch
    recordDf = annotate(inSeq, yaml_file, linear, detailed)
  File "/home/abs/anaconda3/envs/bio/lib/python3.8/site-packages/plannotate/annotate.py", line 355, in annotate
    blastDf = clean(blastDf)
  File "/home/abs/anaconda3/envs/bio/lib/python3.8/site-packages/plannotate/annotate.py", line 178, in clean
    rowSlice = (seqSpace[columnSlice] == kind).any(1) #only the rows that are in the columns of hit
TypeError: any() takes 1 positional argument but 2 were given
```

**Comment by mmcguffi** [comment]
Hi Yuki -- sorry for the troubles. Please refer to #22. I'll try to fix this soon

**Comment by abs-yy** [comment]
Hi! Thanks for the heads up on #22 , I'm sorry that I couldn't catch it.
Downgrading pandas got it to work perfectly, thanks for the big help!

Ah, I moved out of Tokyo Uni a while back forgot to update my bio... Sorry about that

**Comment by nh13** [comment]
Fixing recipe here https://github.com/bioconda/bioconda-recipes/pull/41445

**Comment by mmcguffi** [comment]
Thank you @nh13 for taking care of this -- Ive been traveling since late April without a computer, so I appreciate the effort and fix. 
--Matt

**Comment by nh13** [comment]
How do you live life without a computer? /sarcasm

Do you accept PRs or will that be hard to test/review while you’re away?

**Comment by jeffreybarrick** [comment]
@nh13 We'd be happy to accept PRs.
